### ISSUE TITLE
/currency/latest is returning from 22/10/2020

### ISSUE THREAD

**Issue by juanmaotegui** [gmanriqueUy/cotizaciones-brou#16]
GET /currency/latest and GET currency/2020-12-09 are returning currency from October 22.

`{
    "base": "UYU",
    "timestamp": 1603324800,
    "rates": {
        "ARS": {
            "sell": 0.6,
            "buy": 0.1
        },
        "BRL": {
            "sell": 8.7,
            "buy": 6.7
        },
        "EUR": {
            "sell": 53.51,
            "buy": 47.99
        },
        "USD": {
            "sell": 43.85,
            "buy": 41.45
        }
    }
}`

**Comment by gmanriqueUy** [comment]
Thanks for reporting this! I'll try to take a look tomorrow.

**Comment by lucianolacurcia** [comment]
up

**Comment by gmanriqueUy** [comment]
It should be fixed now. Please let me know if you find any other issue. Thanks!
