### ISSUE TITLE
Cotizaciones intercambiadas

### ISSUE THREAD

**Issue by javico2609** [gmanriqueUy/cotizaciones-brou#2]
Saludos.

Está intercambiando la cotización de EUR con la BRL.

{"base":"UYU","timestamp":1554336000,"rates":{"ARS":{"sell":34.15,"buy":33.43},"BRL":{"sell":39.83,"buy":36.26},"EUR":{"sell":1.1,"buy":0.5},"USD":{"sell":34.45,"buy":33.05}}}

**Comment by gmanriqueUy** [comment]
Parece que modificaron el formato del archivo utilizado para alimentar la base de datos de la API, por eso empezó a retornar valores incorrectos.

Ya lo corregí acá: ed7ebdb0179450ace7230ab5cc38cb6ad2fb903e.

Muchas gracias por reportar esto!
