### ISSUE TITLE
archivo XLS fuente no existe más en la ruta original

### ISSUE THREAD

**Issue by butaca** [gmanriqueUy/cotizaciones-brou#62]
El archivo https://www5.ine.gub.uy/documents/Estadísticaseconómicas/SERIES%20Y%20OTROS/Cotización%20de%20monedas/Cotización%20monedas.xlsx de donde se sacan los datos no existe más, entonces la db no se está actualizando. Estuve buscando y no encontré otra ruta.

Encontré esto https://www.gub.uy/instituto-nacional-estadistica/tematica/cotizacion-monedas pero está vacío.
Acá hay una lista de datos del INE, pero no figuran las cotizaciones: https://www.gub.uy/instituto-nacional-estadistica/estadisticas-economicas.

Me hubiera gustado ser de más ayuda, pero no encontré nada.

**Comment by gmanriqueUy** [comment]
Hola @butaca. Gracias por reportarlo. Costó encontrar la nueva ruta pero ahí quedó actualizado. Saludos!

Edit: Acabo de notar que lo encontré en uno de los links que tú mismo agregaste ahí arriba (el que estaba vacío). Supongo que finalmente lo habrán actualizado.

**Comment by butaca** [comment]
Golazo! Gracias! :)
